# numpy 실습

In [2]:
import numpy as np

In [4]:
np.__version__

'2.2.6'

# numpy 객체 생성

In [11]:
arr = {1,2,3,4,5}
aa = np.array(arr)
aa

array({1, 2, 3, 4, 5}, dtype=object)

In [7]:
type(aa)

numpy.ndarray

In [14]:
len(arr)

5

In [17]:
a = (1,2,3,4,5)
arr = np.array(a)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr.size

5

In [22]:
arr.dtype

dtype('int64')

In [25]:
arr = ['a', 1,2,3,4,5]
aa = np.array(arr)
aa

array(['a', '1', '2', '3', '4', '5'], dtype='<U21')

In [27]:
arr = [1.0, 1,2,3,4,5]
aa = np.array(arr)
aa

array([1., 1., 2., 3., 4., 5.])

# 2차원 데이터 만들기

In [36]:
a2d = [[1,2,3], [4,5,6], [7,8,9]]
a2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
type(a2d)

list

In [40]:
a2d = np.array(a2d)
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# 2차원 -> 행의 갯수
len(a2d)

3

In [41]:
# array의 전체 요소의 갯수
a2d.size

9

In [42]:
a2d.shape

(3, 3)

# Save and Load data

In [43]:
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# 파일로 저장하기
np.save('my_array', a2d)

In [45]:
# 파일로 저장된것 불로오기
arr2d = np.load('my_array.npy')
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# BUILT-IN METHODS AND FUNCTIONS

In [46]:
np.zeros(4)

array([0., 0., 0., 0.])

In [47]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [48]:
# 1차원
np.ones((7,))

array([1., 1., 1., 1., 1., 1., 1.])

In [49]:
# 2차원
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

# 특정 값으로, 행렬 만들기

In [50]:
# np.full(shape, 특정값)
np.full((7,), 5)

array([5, 5, 5, 5, 5, 5, 5])

In [51]:
np.full((7,2),5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [52]:
np.full((4,2,3),5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

# 정수의 배열을 얻고자 할때