# 랜덤값으로 채워진 배열을 만들 수 있다.

In [5]:
import numpy as np

In [6]:
import random

In [39]:
random.random()

0.396058242610681

In [7]:
# 파이썬의 기본 랜덤 라이브러리는 다차원 배열이 안됨
# 랜덤으로 5개의 숫자를 만들고싶음.
np.random.random(5)

array([0.44235644, 0.86482347, 0.24582792, 0.73127645, 0.28517689])

In [8]:
np.random.random((5,))

array([0.67677179, 0.61039625, 0.56396314, 0.33139215, 0.02148656])

In [10]:
# 랜덤 seed
# 0~1사이의 실수로 난수 발생
np.random.random((3,5))

array([[0.58412126, 0.77204591, 0.11394997, 0.88534703, 0.10125574],
       [0.83760091, 0.22013243, 0.04795906, 0.65474957, 0.28786657],
       [0.59069441, 0.75252614, 0.25036853, 0.70557246, 0.85624073]])

In [11]:
random.seed(4)
random.random()

0.23604808973743452

In [12]:
# random.seed(3)
# 랜덤으로 뽑는 숫자가 나오는 패턴을 일치시키는 방법
# 첫번째 실행에 나온숫자, 두번째 실행에 나온숫자, ... => 패턴
# 하나의 셀에만 적용
random.random()

0.1031660342307158

In [13]:
# numpy의 seed 고정 방법, 순서대로 실행하는게 중요함.
np.random.seed(3)

In [14]:
np.random.random((3,5))

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [15]:
np.random.random((3,5))

array([[0.59086282, 0.02398188, 0.55885409, 0.25925245, 0.4151012 ],
       [0.28352508, 0.69313792, 0.44045372, 0.15686774, 0.54464902],
       [0.78031476, 0.30636353, 0.22195788, 0.38797126, 0.93638365]])

# np.random.randint(start, stop, size = shape)  
# 시작값과 끝값을 줄 수 있다.  

In [18]:
np.random.seed(9)

In [19]:
# np.rnadom.seed(9) 실행하고, 한번만 적용
np.random.randint(1, 45, (7,))

array([29, 23,  2, 23, 41, 28, 34], dtype=int32)

In [20]:
np.random.randint(1, 45, (3,4))

array([[30, 29,  1, 25],
       [11, 30, 43, 13],
       [19, 23,  2, 36]], dtype=int32)

In [21]:
# 1~9+1
X = np.random.randint(1, 100, (3,4))

In [25]:
print(X.max())
print(X.min())
print(X.std())
X.var()

81
10
22.687949567018073


np.float64(514.7430555555555)

In [26]:
a = np.array([3,4,5,6,7,8,9,10])
sorted(a.tolist())

[3, 4, 5, 6, 7, 8, 9, 10]

In [27]:
type(a)

numpy.ndarray

In [28]:
# 중앙값 => 데이터를 오름차순으로 정렬한 후, 중간에 있는 값
# 넘파이 객체에는 median이 없음
# 중앙 값이 두개인 경우는 두 값의 평균을 구함.

np.median(a)

np.float64(6.5)

In [29]:
np.random.seed(3)
X = np.random.randint(1, 100, (4,5))
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [30]:
# 각 열별 최대 값을 구하고 싶다.
# [94, 40, 97, 73, 82]
# 가장 큰 값을 구해야 하는 경우

X.max(axis=0)


array([94, 40, 97, 73, 82], dtype=int32)

In [31]:
# 각 행별 최대 값을 구하고 싶다.
# [73, 75, 97, 94]
# 가장 큰 값을 구해야 하는 경우

X.max(axis=1)

array([73, 75, 97, 94], dtype=int32)

In [32]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [33]:
# 원하는 데이터의 갯수를 구하는 방법
# X에서 70보다 큰 데이터는 몇개?
X>70

array([[False, False, False,  True, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False,  True]])

In [34]:
(X>70).sum()

np.int64(5)

In [35]:
# X에서 70보다 큰 데이터들만 가져와
X[X > 70]

array([73, 75, 97, 94, 82], dtype=int32)

In [36]:
X[X > 70].size

5

In [43]:
random.seed(4)
np.random.random((3,5))

array([[0.65363085, 0.66268627, 0.87107205, 0.81122776, 0.37412473],
       [0.07520011, 0.76057848, 0.0637698 , 0.84104116, 0.69263374],
       [0.44590044, 0.36234046, 0.51609462, 0.45733218, 0.80836224]])

In [50]:
random.seed(4)
random.random()

0.23604808973743452

In [46]:
np.random.random((3,5))

array([[0.20696613, 0.92573278, 0.27732305, 0.17606212, 0.99030119],
       [0.69265062, 0.75214003, 0.11621659, 0.08600072, 0.66562461],
       [0.32957136, 0.36165062, 0.526111  , 0.42472996, 0.81978073]])

In [60]:
random.seed(123)
print(random.random())
print(random.random())
print(random.random())
print(random.random())
print(random.random())

0.052363598850944326
0.08718667752263232
0.4072417636703983
0.10770023493843905
0.9011988779516946


In [71]:
random.seed(12)
print(random.random())
print(random.random())
print(random.random())
print(random.random())
print(random.random())

0.4745706786885481
0.6574725026572553
0.6664104711248381
0.14260035292536777
0.01086044309006795


In [73]:
random.seed(12)

In [74]:
print(random.random())

0.4745706786885481


In [75]:
print(random.random())

0.6574725026572553


In [76]:
print(random.random())

0.6664104711248381


In [97]:
# 답
random.seed(12)
random.random()
random.random()
result = random.random()
print(result)

0.6664104711248381


In [98]:
X = np.random.randint(1, 100, (3,4))

In [104]:
X

array([[96, 28, 31, 54],
       [59,  1, 85, 51],
       [90, 33, 88, 31]], dtype=int32)

In [105]:
X.max()

np.int32(96)

In [106]:
X.min()

np.int32(1)

In [107]:
X.mean()

np.float64(53.916666666666664)

In [108]:
X.std()

np.float64(29.147493698239117)

In [109]:
X.var()

np.float64(849.576388888889)

In [111]:
type(X)

numpy.ndarray

In [112]:
np.median(X)

np.float64(52.5)

In [113]:
import numpy as np

np.random.seed(3)
X = np.random.randint(1, 100, (4,5))
print(X)

[[25  4 57 73  1]
 [22 20 75 42 11]
 [22 39 97 21 45]
 [94 40 15 27 82]]


In [114]:
X.max(axis=0)

array([94, 40, 97, 73, 82], dtype=int32)

In [116]:
X.max(axis=1)

array([73, 75, 97, 94], dtype=int32)

In [117]:
# 원하는 데이터의 갯수를 구하는 방법
# X에서 70보다 큰 데이터는 몇개?
X>70

array([[False, False, False,  True, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False,  True]])

In [126]:
(X>70).sum()

np.int64(5)

In [124]:
X[X > 70]

array([73, 75, 97, 94, 82], dtype=int32)

In [127]:
X[X > 70].size

5

In [133]:
a = [1,2,3,4,5]
a = np.array(a)

In [134]:
len(a)

5

In [135]:
a.size

5

In [136]:
b = np.array([[1,2,3],
              [4,5,6]]) # 2행 3열짜리 2차원 배열

print(f"len(b): {len(b)}")       # 출력: len(b): 2
print(f"b.size: {b.size}")

len(b): 2
b.size: 6
